/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness — always 200 unless the process is wedged.
         */
        get: operations["health-health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness — verifies the app can actually serve traffic.
         */
        get: operations["health-ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["auth-register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["auth-login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Clear the HttpOnly access cookie.
         *
         *     Stateless logout: the JWT itself can't be revoked server-side without
         *     introducing a denylist (a Sprint 3 concern). What we *can* do is tell
         *     the browser to drop the cookie so the next request doesn't carry it.
         *     Bearer-token clients have no cookie to clear; they just stop sending
         *     the header.
         */
        post: operations["auth-logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/telegram/link-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Telegram Link Code */
        post: operations["auth-create_telegram_link_code"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/telegram/consume-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Consume Telegram Link Code */
        post: operations["auth-consume_telegram_link_code"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/telegram/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login By Telegram */
        post: operations["auth-login_by_telegram"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the authenticated user.
         *
         *     The response is shaped by ``UserOut`` via FastAPI's ``response_model``;
         *     the typed return is the ORM instance so mypy stays happy without an
         *     explicit conversion.
         */
        get: operations["users-me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/seeker": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Seeker Profile */
        get: operations["profiles-get_seeker_profile"];
        /** Upsert Seeker Profile */
        put: operations["profiles-upsert_seeker_profile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/employer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Employer Profile */
        get: operations["profiles-get_employer_profile"];
        /** Upsert Employer Profile */
        put: operations["profiles-upsert_employer_profile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resumes/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Resume */
        post: operations["resumes-upload_resume"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resumes/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Resume Versions */
        get: operations["resumes-list_resume_versions"];
        put?: never;
        /** Create Resume Version */
        post: operations["resumes-create_resume_version"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vacancies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Vacancies */
        get: operations["vacancies-list_vacancies"];
        put?: never;
        /** Create Vacancy */
        post: operations["vacancies-create_vacancy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vacancies/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Vacancies */
        get: operations["vacancies-list_my_vacancies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vacancies/my/page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Vacancies Page */
        get: operations["vacancies-list_my_vacancies_page"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vacancies/my/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Vacancy Analytics */
        get: operations["vacancies-my_vacancy_analytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vacancies/my/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Vacancy Actions */
        get: operations["vacancies-my_vacancy_actions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vacancies/my/actions/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export My Vacancy Actions Csv */
        get: operations["vacancies-export_my_vacancy_actions_csv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vacancies/search/semantic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Semantic
         * @description Semantic vacancy search via pgvector cosine distance.
         *
         *     Gated on ``plan.semantic_search`` (Pro and Employer plans only). Free
         *     tier callers get 402 ``payment_required`` so the FE can prompt for an
         *     upgrade rather than silently degrade to keyword search — that would
         *     mask why results look "worse" than the user expected.
         *
         *     The route accepts a single ``q`` plus a ``limit`` and returns up to
         *     ``limit`` rows ordered by cosine distance. Filters that the keyword
         *     endpoint exposes (``location``, ``level``, ``stack``) are deliberately
         *     omitted here — the whole point of semantic search is that the
         *     embedding model handles those signals natively. A composite endpoint
         *     that combines both ranking modes can come in a later wave.
         */
        get: operations["vacancies-search_semantic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vacancies/{vacancy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Vacancy
         * @description Public detail endpoint — replaces the client-side list-scan workaround.
         *
         *     Returns 404 for missing/soft-deleted rows. Live hh.ru records aren't
         *     represented here (they're synthesised in :func:`list_vacancies`); IDs from
         *     that path won't resolve, which is the correct behaviour.
         */
        get: operations["vacancies-get_vacancy"];
        /** Update My Vacancy */
        put: operations["vacancies-update_my_vacancy"];
        post?: never;
        /** Delete My Vacancy */
        delete: operations["vacancies-delete_my_vacancy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vacancies/{vacancy_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive My Vacancy */
        post: operations["vacancies-archive_my_vacancy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vacancies/{vacancy_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish My Vacancy */
        post: operations["vacancies-publish_my_vacancy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vacancies/{vacancy_id}/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Promote My Vacancy */
        post: operations["vacancies-promote_my_vacancy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/{source_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Source */
        post: operations["ingest-ingest_source"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["ingest-list_sources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/digest/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Digest Preferences */
        get: operations["digest-get_digest_preferences"];
        /** Update Digest Preferences */
        put: operations["digest-update_digest_preferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/digest/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview Digest */
        get: operations["digest-preview_digest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ai Chat */
        post: operations["ai-ai_chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ai Chat Stream
         * @description Stream the AI gate decision + LLM-driven filters + assistant reply over SSE.
         */
        post: operations["ai-ai_chat_stream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/run-scheduler": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Scheduler Once */
        post: operations["admin-run_scheduler_once"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Plans
         * @description Public catalog — used by the pricing page and Telegram bot.
         */
        get: operations["billing-list_plans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Subscription */
        get: operations["billing-my_subscription"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Checkout */
        post: operations["billing-create_checkout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Subscription */
        post: operations["billing-cancel_subscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/yookassa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Yookassa Webhook
         * @description Process payment notifications from ЮKassa.
         *
         *     Handled events:
         *
         *     * ``payment.succeeded``     — flip the subscription to ``active``,
         *       capture the saved ``payment_method.id`` for recurring renewals.
         *     * ``payment.canceled``      — flip to ``canceled``; access keeps until
         *       ``current_period_end`` (set by the previous success, if any).
         *     * ``refund.succeeded``      — full refund: clear the period end and the
         *       saved payment method so the user is back to free immediately.
         *
         *     Unknown event types are ack'd with 200 to stop ЮKassa retrying — the
         *     provider treats any non-2xx response as a retryable failure, and we'd
         *     rather log + drop than build up a retry queue we don't read.
         */
        post: operations["webhooks-yookassa_webhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AiChatRequest */
        AiChatRequest: {
            /** Message */
            message: string;
        };
        /** AiChatResponse */
        AiChatResponse: {
            /** Accepted */
            accepted: boolean;
            /** Message */
            message: string;
            /** Extracted Filters */
            extracted_filters?: {
                [key: string]: string;
            } | null;
        };
        /** Body_resumes-upload_resume */
        "Body_resumes-upload_resume": {
            /** File */
            file: string;
        };
        /**
         * CheckoutRequest
         * @description Body for ``POST /billing/checkout`` — pick the target plan by slug.
         */
        CheckoutRequest: {
            /** Plan Slug */
            plan_slug: string;
            /** Return Url */
            return_url?: string | null;
        };
        /** CheckoutResponse */
        CheckoutResponse: {
            /** Confirmation Url */
            confirmation_url: string;
            /** Payment Id */
            payment_id: string;
            /** Status */
            status: string;
        };
        /** DigestItem */
        DigestItem: {
            /** Vacancy Id */
            vacancy_id: number;
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Location */
            location: string;
            /** Score Reason */
            score_reason: string;
        };
        /** DigestPreferenceOut */
        DigestPreferenceOut: {
            /**
             * Frequency
             * @enum {string}
             */
            frequency: "daily" | "weekly";
            /** Via Telegram */
            via_telegram: boolean;
            /** Via Email */
            via_email: boolean;
            /** Telegram Chat Id */
            telegram_chat_id: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DigestPreferenceUpdate */
        DigestPreferenceUpdate: {
            /**
             * Frequency
             * @default daily
             * @enum {string}
             */
            frequency: "daily" | "weekly";
            /**
             * Via Telegram
             * @default true
             */
            via_telegram: boolean;
            /**
             * Via Email
             * @default false
             */
            via_email: boolean;
            /** Telegram Chat Id */
            telegram_chat_id?: string | null;
        };
        /** DigestPreviewOut */
        DigestPreviewOut: {
            /**
             * Frequency
             * @enum {string}
             */
            frequency: "daily" | "weekly";
            /** Channels */
            channels: string[];
            /** Items */
            items: components["schemas"]["DigestItem"][];
        };
        /** EmployerActionLogOut */
        EmployerActionLogOut: {
            /** Id */
            id: number;
            /** Vacancy Id */
            vacancy_id: number | null;
            /** Action */
            action: string;
            /** Meta */
            meta: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** EmployerProfileOut */
        EmployerProfileOut: {
            /** Company Name */
            company_name: string;
            /** Website */
            website: string;
            /** Description */
            description: string;
            /** Verified */
            verified: boolean;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** EmployerProfileUpdate */
        EmployerProfileUpdate: {
            /**
             * Company Name
             * @default
             */
            company_name: string;
            /**
             * Website
             * @default
             */
            website: string;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** EmployerVacancyAnalyticsOut */
        EmployerVacancyAnalyticsOut: {
            /** Total */
            total: number;
            /** Active */
            active: number;
            /** Archived */
            archived: number;
        };
        /** EmployerVacancyPageOut */
        EmployerVacancyPageOut: {
            /** Items */
            items: components["schemas"]["VacancyOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestRunOut */
        IngestRunOut: {
            /** Id */
            id: number;
            /** Source */
            source: string;
            /** Fetched Count */
            fetched_count: number;
            /** Inserted Count */
            inserted_count: number;
            /** Deduped Count */
            deduped_count: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * PlanOut
         * @description Public plan info — exposed via ``GET /billing/plans``.
         */
        PlanOut: {
            /** Slug */
            slug: string;
            /** Name Ru */
            name_ru: string;
            /** Price Rub */
            price_rub: number;
            /** Ai Daily Limit */
            ai_daily_limit: number;
            /** Semantic Search */
            semantic_search: boolean;
            /** Digest Frequency */
            digest_frequency: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Role
             * @enum {string}
             */
            role: "seeker" | "employer";
        };
        /** ResumeOut */
        ResumeOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Parsed Skills */
            parsed_skills: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ResumeVersionCreate */
        ResumeVersionCreate: {
            /** Name */
            name: string;
            /**
             * Target Role
             * @default
             */
            target_role: string;
            /** Content */
            content: {
                [key: string]: unknown;
            };
        };
        /** ResumeVersionOut */
        ResumeVersionOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Target Role */
            target_role: string;
            /** Content */
            content: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SchedulerRunOut */
        SchedulerRunOut: {
            /** Ingestion Runs */
            ingestion_runs: number;
            /** Ingestion Inserted */
            ingestion_inserted: number;
            /** Ingestion Deduped */
            ingestion_deduped: number;
            /** Digests Sent */
            digests_sent: number;
            /** Digests Skipped */
            digests_skipped: number;
            /** Digests Failed */
            digests_failed: number;
        };
        /** SeekerProfileOut */
        SeekerProfileOut: {
            /** Full Name */
            full_name: string;
            /** Target Role */
            target_role: string;
            /** Location */
            location: string;
            /** About */
            about: string;
            /** Skills */
            skills: string[];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SeekerProfileUpdate */
        SeekerProfileUpdate: {
            /**
             * Full Name
             * @default
             */
            full_name: string;
            /**
             * Target Role
             * @default
             */
            target_role: string;
            /**
             * Location
             * @default
             */
            location: string;
            /**
             * About
             * @default
             */
            about: string;
            /**
             * Skills
             * @default []
             */
            skills: string[];
        };
        /** SourceConnectorOut */
        SourceConnectorOut: {
            /** Name */
            name: string;
        };
        /**
         * SubscriptionOut
         * @description Current subscription state of the authenticated user.
         */
        SubscriptionOut: {
            plan: components["schemas"]["PlanOut"];
            /** Status */
            status: string;
            /** Current Period End */
            current_period_end: string | null;
            /**
             * Cancel At Period End
             * @default false
             */
            cancel_at_period_end: boolean;
        };
        /** TelegramBotLoginRequest */
        TelegramBotLoginRequest: {
            /** Telegram User Id */
            telegram_user_id: string;
            /** Telegram Chat Id */
            telegram_chat_id: string;
        };
        /** TelegramLinkCodeOut */
        TelegramLinkCodeOut: {
            /** Code */
            code: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** TelegramLinkConsumeRequest */
        TelegramLinkConsumeRequest: {
            /** Code */
            code: string;
            /** Telegram User Id */
            telegram_user_id: string;
            /** Telegram Chat Id */
            telegram_chat_id: string;
            /** Telegram Username */
            telegram_username?: string | null;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Role
             * @enum {string}
             */
            role: "seeker" | "employer";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** VacancyCreateRequest */
        VacancyCreateRequest: {
            /** Source */
            source: string;
            /** External Id */
            external_id: string;
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Location */
            location: string;
            /**
             * Employment Type
             * @default full-time
             */
            employment_type: string;
            /**
             * Experience Level
             * @default middle
             */
            experience_level: string;
            /** Salary From */
            salary_from?: number | null;
            /** Salary To */
            salary_to?: number | null;
            /**
             * Currency
             * @default RUB
             */
            currency: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Applications Count
             * @default 0
             */
            applications_count: number;
        };
        /** VacancyOut */
        VacancyOut: {
            /** Id */
            id: number;
            /** Source */
            source: string;
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Location */
            location: string;
            /** Employment Type */
            employment_type: string;
            /** Experience Level */
            experience_level: string;
            /** Salary From */
            salary_from: number | null;
            /** Salary To */
            salary_to: number | null;
            /** Currency */
            currency: string;
            /** Description */
            description: string;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Applications Count */
            applications_count: number;
            /** Is Active */
            is_active: boolean;
            /** Archived At */
            archived_at: string | null;
            /** Is Deleted */
            is_deleted: boolean;
            /** Deleted At */
            deleted_at: string | null;
            /** Is Promoted */
            is_promoted: boolean;
            /** Promotion Expires At */
            promotion_expires_at: string | null;
            /** External Url */
            external_url?: string | null;
        };
        /** VacancyPromoteRequest */
        VacancyPromoteRequest: {
            /**
             * Days
             * @default 7
             */
            days: number;
        };
        /** VacancyUpdateRequest */
        VacancyUpdateRequest: {
            /** Title */
            title?: string | null;
            /** Company */
            company?: string | null;
            /** Location */
            location?: string | null;
            /** Employment Type */
            employment_type?: string | null;
            /** Experience Level */
            experience_level?: string | null;
            /** Salary From */
            salary_from?: number | null;
            /** Salary To */
            salary_to?: number | null;
            /** Currency */
            currency?: string | null;
            /** Description */
            description?: string | null;
            /** Applications Count */
            applications_count?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "health-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    "health-ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    "auth-register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "auth-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "auth-logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "auth-create_telegram_link_code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                proshli_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramLinkCodeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "auth-consume_telegram_link_code": {
        parameters: {
            query?: never;
            header?: {
                "x-bot-service-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramLinkConsumeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "auth-login_by_telegram": {
        parameters: {
            query?: never;
            header?: {
                "x-bot-service-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramBotLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "users-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                proshli_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "profiles-get_seeker_profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                proshli_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeekerProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "profiles-upsert_seeker_profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                proshli_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeekerProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeekerProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "profiles-get_employer_profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                proshli_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployerProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "profiles-upsert_employer_profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                proshli_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployerProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployerProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "resumes-upload_resume": {
        parameters: {
            query: {
                name: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                proshli_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_resumes-upload_resume"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "resumes-list_resume_versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                proshli_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeVersionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "resumes-create_resume_version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                proshli_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeVersionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeVersionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "vacancies-list_vacancies": {
        parameters: {
            query?: {
                source?: string | null;
                location?: string | null;
                stack?: string | null;
                level?: string | null;
                min_salary?: number | null;
                max_age_days?: number | null;
                max_applications?: number | null;
                work_mode?: string | null;
                include_archived?: boolean;
                include_live_hh?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VacancyOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "vacancies-create_vacancy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                proshli_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VacancyCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VacancyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "vacancies-list_my_vacancies": {
        parameters: {
            query?: {
                status?: string;
                sort_by?: string;
                order?: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                proshli_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VacancyOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "vacancies-list_my_vacancies_page": {
        parameters: {
            query?: {
                status?: string;
                sort_by?: string;
                order?: string;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                proshli_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployerVacancyPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "vacancies-my_vacancy_analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                proshli_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployerVacancyAnalyticsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "vacancies-my_vacancy_actions": {
        parameters: {
            query?: {
                vacancy_id?: number | null;
                action?: string | null;
                created_from?: string | null;
                created_to?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                proshli_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployerActionLogOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "vacancies-export_my_vacancy_actions_csv": {
        parameters: {
            query?: {
                action?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                proshli_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "vacancies-search_semantic": {
        parameters: {
            query: {
                /** @description Search text */
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                proshli_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VacancyOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "vacancies-get_vacancy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vacancy_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VacancyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "vacancies-update_my_vacancy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vacancy_id: number;
            };
            cookie?: {
                proshli_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VacancyUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VacancyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "vacancies-delete_my_vacancy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vacancy_id: number;
            };
            cookie?: {
                proshli_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "vacancies-archive_my_vacancy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vacancy_id: number;
            };
            cookie?: {
                proshli_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "vacancies-publish_my_vacancy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vacancy_id: number;
            };
            cookie?: {
                proshli_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "vacancies-promote_my_vacancy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vacancy_id: number;
            };
            cookie?: {
                proshli_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VacancyPromoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "ingest-ingest_source": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_name: string;
            };
            cookie?: {
                proshli_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "ingest-list_sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceConnectorOut"][];
                };
            };
        };
    };
    "digest-get_digest_preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                proshli_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestPreferenceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "digest-update_digest_preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                proshli_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DigestPreferenceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestPreferenceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "digest-preview_digest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                proshli_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestPreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "ai-ai_chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                proshli_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "ai-ai_chat_stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                proshli_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "admin-run_scheduler_once": {
        parameters: {
            query?: {
                frequency?: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                proshli_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulerRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "billing-list_plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"][];
                };
            };
        };
    };
    "billing-my_subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                proshli_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "billing-create_checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                proshli_access?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "billing-cancel_subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                proshli_access?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "webhooks-yookassa_webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
