import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import tokens from "./tokens.json" with { type: "json" };

type TokenValue = string | number;
type TokenTree = { [key: string]: TokenValue | TokenTree };

const ROOT = dirname(fileURLToPath(import.meta.url));
const DIST = resolve(ROOT, "dist");

mkdirSync(DIST, { recursive: true });

// --- 1. Flatten tokens for CSS custom properties ---
function flatten(node: TokenTree, prefix: string[] = []): Array<[string, TokenValue]> {
  return Object.entries(node).flatMap(([key, value]) => {
    const path = [...prefix, key];
    if (typeof value === "object" && value !== null) {
      return flatten(value as TokenTree, path);
    }
    return [[`--${path.join("-")}`, value as TokenValue]];
  });
}

const flat = flatten(tokens as TokenTree);

// --- 2. CSS file: :root { --color-app-dark-bg-primary: #0a0a0b; ... } ---
const css = `:root {\n${flat.map(([k, v]) => `  ${k}: ${v};`).join("\n")}\n}\n`;
writeFileSync(resolve(DIST, "tokens.css"), css);

// --- 3. CJS Tailwind preset ---
const tailwindPreset = `// AUTOGENERATED — do not edit. Source: tokens.json
module.exports = {
  theme: {
    extend: {
      colors: ${JSON.stringify(tokens.color, null, 2)},
      spacing: ${JSON.stringify(tokens.spacing, null, 2)},
      borderRadius: ${JSON.stringify(tokens.radius, null, 2)},
      fontFamily: ${JSON.stringify(tokens.font.family, null, 2)},
      fontSize: ${JSON.stringify(tokens.font.size, null, 2)},
      fontWeight: ${JSON.stringify(tokens.font.weight, null, 2)},
      lineHeight: ${JSON.stringify(tokens.font.leading, null, 2)},
      letterSpacing: ${JSON.stringify(tokens.font.tracking, null, 2)},
      boxShadow: ${JSON.stringify(tokens.shadow, null, 2)},
      transitionDuration: ${JSON.stringify(tokens.motion.duration, null, 2)},
      transitionTimingFunction: ${JSON.stringify(tokens.motion.easing, null, 2)},
    },
  },
};
`;
writeFileSync(resolve(DIST, "tailwind.cjs"), tailwindPreset);

console.log(`design-tokens: built ${flat.length} CSS vars + Tailwind preset → dist/`);
